[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "lfgpy"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
lfg-server = "lfgpy.server:main"
lfg-client = "lfgpy.client:main"

[dependency-groups]
dev = ["ipython>=9.3.0", "mypy>=1.16.1", "pytest>=8.4.1", "ruff>=0.12.0"]

[tool.pytest.ini_options]
addopts = "-m 'not integration'"
markers = ["integration"]
